### ISSUE TITLE
mikutter -v not working in cronjob anymore

### ISSUE THREAD

**Issue by JPRuehmann** [mikutter/mikutter#8]
Hello
since I´ve changed from develop to hotfix/3.5 mikutter -v is not working anymore in cronjobs.

**Comment by toshia** [comment]
What is output in stdout or stderr? (no output, abort silently or can you get backtrace with --debug switch?)

Sorry the reply was delayed and I can't test it because vacation :)
Thanks

**Comment by JPRuehmann** [comment]
/var/lib/gems/2.3.0/gems/gtk2-3.1.6/lib/gtk2.rb:13:in `init': Cannot open display:   (Gtk::InitError)
	from /var/lib/gems/2.3.0/gems/gtk2-3.1.6/lib/gtk2.rb:13:in `<top (required)>'
	from /usr/share/mikutter/core/plugin/gtk/gtk.rb:5:in `require'
	from /usr/share/mikutter/core/plugin/gtk/gtk.rb:5:in `<top (required)>'
	from /usr/share/mikutter/core/miquire_plugin.rb:155:in `load'
	from /usr/share/mikutter/core/miquire_plugin.rb:155:in `load'
	from /usr/share/mikutter/core/miquire_plugin.rb:148:in `block in load'
	from /usr/share/mikutter/core/miquire_plugin.rb:146:in `each'
	from /usr/share/mikutter/core/miquire_plugin.rb:146:in `load'
	from /usr/share/mikutter/core/miquire_plugin.rb:148:in `block in load'
	from /usr/share/mikutter/core/miquire_plugin.rb:146:in `each'
	from /usr/share/mikutter/core/miquire_plugin.rb:146:in `load'
	from /usr/share/mikutter/core/miquire_plugin.rb:98:in `block in load_all'
	from /usr/share/mikutter/core/miquire_plugin.rb:38:in `block in each_spec'
	from /usr/share/mikutter/core/miquire_plugin.rb:33:in `each'
	from /usr/share/mikutter/core/miquire_plugin.rb:33:in `each'
	from /usr/share/mikutter/core/miquire_plugin.rb:36:in `each_spec'
	from /usr/share/mikutter/core/miquire_plugin.rb:96:in `load_all'
	from /usr/share/mikutter/core/boot/load_plugin.rb:10:in `<top (required)>'
	from /usr/share/mikutter/core/miquire.rb:98:in `require'
	from /usr/share/mikutter/core/miquire.rb:98:in `miquire_original_require'
	from /usr/share/mikutter/core/miquire.rb:95:in `file_or_directory_require'
	from /usr/share/mikutter/core/miquire.rb:76:in `block in miquire'
	from /usr/share/mikutter/core/miquire.rb:75:in `each'
	from /usr/share/mikutter/core/miquire.rb:75:in `miquire'
	from /usr/share/mikutter/core/miquire.rb:18:in `miquire'
	from ./mikutter.rb:41:in `<main>'

**Comment by JPRuehmann** [comment]
Is it right that -v won´t work completely in the new Versions?
That is no good Idea. because sometimes it is the best way to get the Version for example for Support.

**Comment by osak** [comment]
@JPRuehmann Probably this issue is fixed with commit 29c4ee, which changes the order of processing options. Can you close this ticket if it's solved?

**Comment by JPRuehmann** [comment]
No, nothings changed.
I am using 3.5.15 -v still not working.

**Comment by Akkiesoft** [comment]
-v works fine for me any patterns.

```
akkie@Soful:~/mikutter (hotfix/3.5) $ ruby mikutter.rb -v
mikutter 3.5.15
akkie@Soful:~/mikutter (hotfix/3.5) $ ruby mikutter.rb --version
mikutter 3.5.15
akkie@Soful:~/mikutter (hotfix/3.5) $ ./mikutter.rb -v
mikutter 3.5.15
akkie@Soful:~/mikutter (hotfix/3.5) $ ./mikutter.rb --version
mikutter 3.5.15
```

Also works fine in cronjob. For example, I tried in Raspberry Pi (Raspbian Stretch.) and I wrote crontab below.

```
$ crontab -e

* * * * * /usr/bin/ruby /home/pi/mikutter/mikutter.rb -v > /home/pi/version.txt

$ cat version.txt
mikutter 3.5.15
```

Could you paste your cronjobs what you tried?

**Comment by JPRuehmann** [comment]
Sorry
It was my fault, I am starting mikutter via a Script, so that it works as normal Command.
I forgot to pass the Commandline Parameter to mikutter.rb.
Now it works.
Thanks,
